# Generated by Django 5.2.14 on 2026-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
